name: tcb_challenge
description: Code challenge app for The Code Brothers
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  app_ui:
    path: packages/app_ui
  bloc: ^8.0.3
  cached_network_image: ^3.2.0
  comments_repository:
    path: packages/comments_repository
  equatable: ^2.0.3
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  photos_repository:
    path: packages/photos_repository

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.0.3
  flutter_gen_runner: ^4.1.5
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true

flutter_gen:
  output: lib/generated/
  lineLength: 80

  integrations:
    flutter_svg: true
